global: 
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'quiz-master'

scrape_configs: 
  - job_name: 'quiz-master'
    scrape_interval: 5s
    static_configs:
      - targets: ['quiz-master:5000']