apiVersion: v1
kind: Service
metadata:
  name: quiz-master
spec:
  selector:
    app: quiz-master
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002
