apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-master
  template:
    metadata:
      labels:
        app: quiz-master
    spec:
      containers:
        - name: quiz-master
          image: sampaniony/quiz-master:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
